# Generated by Django 5.1.4 on 2024-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_membership_overduereport_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='REQUESTED', max_length=20),
        ),
    ]
